[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
verbosity = 3

[fmt]
line_length = 100

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[profile.private_keys]
deployer = "${DEPLOYER_PRIVATE_KEY}"


# [rpc_endpoints]
# base = "${BASE_SEPOLIA_RPC_URL}"
# goerli = "${GOERLI_RPC_URL}"
# sepolia = "${SEPOLIA_RPC_URL}"
# mumbai = "${MUMBAI_RPC_URL}"
# mainnet = "${MAINNET_RPC_URL}"
# polygon = "${POLYGON_RPC_URL}"

# [etherscan]
# base = { key = "${BASESCAN_API_KEY}" }
# goerli = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
# mumbai = { key = "${POLYGONSCAN_API_KEY}" }
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
# polygon = { key = "${POLYGONSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
